### ISSUE TITLE
Support for passwordless connection email template

### ISSUE THREAD

**Issue by VincentHoang** [alexkappa/terraform-provider-auth0#118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Normally, you can provide an email template via the email template endpoint. However, for some reason you can't set an email template for passwordless. 

In order to setup a custom email for passwordless, you need to use the connections endpoint (I don't see this documented anywhere, but that's how it's done when using the dashboard > connections > passwordless > email).

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "passwordless" {
  name = "Passwordless-Connection"
  strategy = "email"
  options {
    ...
    email {
      body = "..."
      from = "{{ application.name }} <root@auth0.com>"
      subject = "Welcome to {{ application.name }}"
      syntax = "liquid"
    }
    ...
  }
}
```

**Comment by alexkappa** [comment]
@VincentHoang do you mean adding the necessary fields to the connection resource? Indeed it doesn't seem to be documented by Auth0 but the app uses these fields to specify passwordless templates. A PR is welcomed if you can.

**Comment by victorb** [comment]
I'm also interested in having this feature, will give a PR a try if I have spare time.

Something I noticed in the meantime, is that if you use the `email` strategy with this provider, it breaks the UI and the email templates, as Terraform is not passing enough attributes and seems the Auth0 API assumes you want to remove attributes if they are not passed.

So trying to use this provider with `email` right now seems to be breaking stuff in Auth0. Trying to figure out how to work around this now.

**Comment by dimitrit** [comment]
@alexkappa FYI I have implemented this in my [fork](https://github.com/dimitrit/auth0) of this project. I will wait for my auth0 library PR to be merged before creating a PR for this.

**Comment by yinzara** [comment]
ROFL I literally just started to implement this myself. 

Ok so there's an issue.  

The Auth0 Golang library has just upgraded a major version to version 4.  I don't know if they'll accept a submission to add fields to version 3 so it might be a problem.

If we do want to upgrade to v4, I tested and all resources except Connection did not require a code change (other than changing the import).  The problem is that the Connection has now changed fundamentally.

The "Strategy" is not just an `interface{}` and can be one of 13 different structs (many of which share fields).  Since the Go library requires that you pass it the real structs for each of the types, there is no way we could write a "generic" connection. This means we would either need to completely rewrite the "auth0_connection" resource OR we could choose to create a resource for each variation.  

i.e. 
"auth0_database_connection" or "auth0_email_connection"
 "auth0_connection_email" or "auth0_email_connection"
"auth0_google_oauth2_connection" or "auth0_connection_google_oauth2"

**Comment by yinzara** [comment]
I actually wrote a whole different response then saw Alex's changes for v4.

I think we're starting to get to a state where the "auth0_connection" does not mirror the Auth0 Go library anymore.   The generic 'options' now can be of 13 different types in which some of those types share field names that are of different types.  For example, the "email" connection type has an "email" option that is an object with 4 fields: subject, from, body and syntax. 

However for the "google-oauth2" connection type, the "email" field is a boolean.

I propose we create new configuration option sections that are specific to the type of option.

We can leave the existing "options" to allow for legacy configuration and add new "google_oauth2_options", "email_options", "github_options" etc.

This will allow the terraform provider to match the new library structure better. It will also make the provider easier to understand what the options are that are available.
