### ISSUE TITLE
0.5.2 release binaries don't include version number in filename

### ISSUE THREAD

**Issue by garry-jeromson** [alexkappa/terraform-provider-auth0#176]
The file naming convention for Terraform plugin binaries is `terraform-provider-<NAME>_vX.Y.Z` (see https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions). Up until version 0.5.1, the release binaries available here on GitHub had this naming format; for version 0.5.2, the version tag is missing.

This would be nice to have, so that the binaries can be directly extracted into the destination plugin folder with a version number, without having to rename them. (Explicitly specifying the version is particularly useful now that the plugin is an official Terraform provider, as it allows users to override the default latest version.)

**Comment by alexkappa** [comment]
It seems like when cloning the repository over to terraform-providers/terraform-provider-auth0 the [`.goreleaser.yml` file has been removed](https://github.com/alexkappa/terraform-provider-auth0/blob/3487b51e82824bf0dcd8f333d05d4d1978c9fb17/.goreleaser.yml). Likely because it conflicts with terraforms internal tooling.

So prior releases should have both `CGO_ENABLED=0` as well as the proper naming scheme. I'll have a look if we can define these properties without the use of a `.goreleaser.yml` so we can test some releases in this repo as well.

**Comment by alexkappa** [comment]
I've brought it back and re-released 0.5.2 in the same way I've done in the past. Please give it a try and let me know if it works for you.

**Comment by garry-jeromson** [comment]
Works like a charm with the old release flow!
