### ISSUE TITLE
idle_session_timeout can be a fraction of an hour

### ISSUE THREAD

**Issue by srenatus** [alexkappa/terraform-provider-auth0#233]
## Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* auth0_tenant

### Terraform Configuration Files

The resource settings don't include `idle_session_timeout` right now, so it's
```hcl
resource "auth0_tenant" "dev-tenant" {
  friendly_name = "Dev Tenant"

  # number of hours a session is valid
  session_lifetime = 12
}
```

In auth0's management UI, it's set to 30 minutes:
![image](https://user-images.githubusercontent.com/870638/81684063-eea35000-9456-11ea-97e1-d4e04e744f05.png)

### Expected Behavior

It should not explode 😉 

### Actual Behavior

```
# terraform apply -auto-approve
module.tenant.auth0_tenant.dev-tenant: Refreshing state... [id=terraform-20200512113443006900000001]
module.webapp.auth0_client.local-webapp: Refreshing state... [id=BQpS1FDWpIU5iw779X63gvB3f2LFM6h2]
module.connection.auth0_connection.main-connection: Refreshing state... [id=con_j4zs05ANTO69Yj7U]

Error: json: cannot unmarshal number 0.5 into Go struct field Tenant.idle_session_lifetime of type int
```
### Steps to Reproduce

1. `terraform apply`

**Comment by bergbrains** [comment]
I ran into this too, when the `Inactivity timeout` is < 60.  Works at 60, but if it's set to 59, I get this: 

`Error: json: cannot unmarshal number 0.9833333333333333 into Go struct field Tenant.idle_session_lifetime of type int`

**Comment by alexkappa** [comment]
Hi everyone, thanks for submitting this issue and let me know. It seems that the `session_lifetime` field can be set to fractions and the SDK did not expect that.

The solution here seems to be to change the datatype to float instead of int so that marshal/unmarshal does not break. We have to consider backwards compatibility however for folks who have used the provider with a `TypeInt` schema which will become a `TypeFloat`. My gut feeling is that should not be too hard to do, but we shouldn't rush this in and make sure we're not breaking peoples code.

**Comment by mattcosta7** [comment]
not stale, this is still not supportede

**Comment by mattcosta7** [comment]
This closed, but still isn't supported

**Comment by alexkappa** [comment]
Sorry folks, re-opening.

**Comment by alexkappa** [comment]
After some investigation I am able to reproduce the issue. However the problem is a little more involved as I'd have hoped.

The root of the problem seems to be the UI setting at:
`https://manage.auth0.com/dashboard/eu/<my-tenant>/tenant/advanced`.

<img width="1043" alt="Screen Shot 2020-11-02 at 18 27 48" src="https://user-images.githubusercontent.com/1204095/97899371-85cbcf00-1d39-11eb-896c-cd9b5ea19852.png">

Saving this will trigger the following request:

```
> PATCH /api/tenants/settings
>
> {"idle_session_lifetime_in_minutes":30,"session_lifetime_in_minutes":64800,"flags":{"enable_sso":false}}
*
< { "...", "idle_session_lifetime": 0.5, "session_lifetime": 1080, "..."}
```

Notice how the fields have a `_in_minutes` suffix. When these values are read back, the original field names are used instead, divided by 60. This is an awkward implementation of the Management API and an undocumented one at that.

I'm working on a [PR](https://github.com/go-auth0/auth0/pull/156) to fix this in go-auth0/auth0 and once done, I'll give this some time.

**Comment by srenatus** [comment]
> This is an awkward implementation of the Management API and an undocumented one at that.

Indeed! 😓 

Thanks for working on this!

**Comment by bergbrains** [comment]
I'm writing a work-around script to PATCH idle_session_lifetime, thinking that it was simply a matter of treating the value of that param as a proper float, however I found a reasonable work-around and some interesting inconsistencies.

Regarding the work-around, `idle_session_lifetime` (hours) and `idle_session_lifetime_in_minutes` parameters to set the same value in the tenant.  They both take ints.  However, that distinction is not respected consistently in the return value of `GET idle_session_lifetime`, which returns ints for even hours, but floats for fractional values.  There is no 

By setting `idle_session_lifetime` to full hours of minutes (divisible by 60), it returns the value as an int, but if it's not full hours, it will return floats:

Setting the value of `idle_session_lifetime_in_minutes` to `12` returns this:

`"idle_session_lifetime": 0.2,`

Whereas setting `idle_session_lifetime` to `1` shows as 60 in the UI and 1 in the GET tenant output:

`"idle_session_lifetime": 1,`

Also, `PATCH tenant` barfs on floats in `idle_session_lifetime`, even though it returns a float -- sometimes.

So, we can -- if we want to draw outside the documented-API-box -- change `idle_session_lifetime` to a float, to allow the sometimes-floats to be read, but when setting values, it's probably easiest to always use `idle_session_lifetime_in_minutes`.

Supporting both parameters in the resource might be helpful as well.

WRT backwards compatibility, introducing floatism to a previously-int, could cause problems for existing code, though I question what the impact of that might be beyond TF.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/18 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
