### ISSUE TITLE
`auth0_client` terraform state does not update on description change

### ISSUE THREAD

**Issue by nrmitchi** [alexkappa/terraform-provider-auth0#295]
### Description
I have an `auth0_client`, and modified the `description`. The terraform state is not updated, meaning the modified resource re-appears in all subsequent `plan`'s.

### Terraform Version

```
Terraform v0.12.24
+ provider.auth0 v0.14.0
```
### Affected Resource(s)

* auth0_client

### Expected Behavior
When the resource state in Auth0 is updated, the terraform state is updated.

### Actual Behavior
The resource state in Auth0 is updated, but the terraform state is not modified.

### Steps to Reproduce

1. Create a auth0_client with a description
2. Update the description with an apply
3. Do another plan and see that the state is not clean

**Comment by nrmitchi** [comment]
Looking further, this seems to only occur when the new description is missing/empty/null. 

I suspect this may be the same root cause as #289 (`json:",omitempty"`).

**Comment by alexkappa** [comment]
Thanks for reporting @nrmitchi, I can confirm the issue occurs when changing a value to its "zero" value (in this case `""`). See this gist on how I've verified: https://gist.github.com/alexkappa/adca2fbae286dabe1fcfce5e2682c544.

I am not sure however how this provider is supposed to handle this. Internally we rely on Terraform's [`ResourceData.GetOk`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema#ResourceData.GetOk) method to check whether the value of `description` has been set to a non zero value, which states:

> GetOk returns the data for the given key and whether or not the key has been set to a non-zero value at some point.

I wonder what "at some point" means in this context, because to me it sounds like after being set to a non-zero initially, subsequent calls to GetOk should return `true`.

**Comment by sergiught** [comment]
This relates to several other issues that are present within the provider and I have captured this along with the others within https://github.com/auth0/terraform-provider-auth0/issues/14. 

As this repo has moved over at https://github.com/auth0/terraform-provider-auth0 please open new issues over there from now on.
