### ISSUE TITLE
Add Support to M1 macs

### ISSUE THREAD

**Issue by luisrudge** [alexkappa/terraform-provider-auth0#355]
### Description

Currently, we can't use this with M1 macs.

```
Provider registry.terraform.io/alexkappa/auth0 v0.17.1 does not have a package
available for your current platform, darwin_arm64.
```

**Comment by yvovandoorn** [comment]
Hi @luisrudge 

The good news is that the release.yml () is already updated to start building it when GitHub has the hardware in place. 

However we are dependent on https://github.com/actions/virtual-environments/issues/2187 and https://github.com/actions/runner/issues/805 as the project uses GitHub Actions cloud environment. 

Once the infra is in place, you will start seeing builds of this project (and likely any other utilizing GitHub Actions) be compatible. 

Leaving issue open until GitHub has support for M1 Mac builds.

**Comment by 0x91** [comment]
@yvovandoorn goreleaser/golang will cross compile. Is there a reason why this isn't working already?

**Comment by yvovandoorn** [comment]
Hi @0x91 I'm constrained in my own ability to get this to work. Could you point me to a project where this is working so I can see what needs to be done here. 

Thanks!

**Comment by alexkappa** [comment]
Our [goreleaser](https://github.com/alexkappa/terraform-provider-auth0/blob/master/.github/release.yml) configuration should allow for building darwin/arm64, but we were probably missing out since our Go version was a little outdated during the [release](https://github.com/alexkappa/terraform-provider-auth0/blob/master/.github/workflows/release.yml#L18) process

If we update to Go 1.16 we should start seeing darwin/arm64 release artifacts.
