### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by nitrag** [alexkappa/terraform-provider-auth0#368]
For `auth0_custom_domain`, what exactly is `verification_method` = `txt` doing now that Auth0 seems to only do CNAME verification now?

Also, how can we do verification in terraform? Similar to: `aws_acm_certificate_validation` 

1. Create custom domain with: `auth0_custom_domain`
2. Create CNAME record (AWS Route53) with: `aws_route53_record` and `....verification[0].methods[0].record`
3. ??? How to verify automatically, at least on subsequent runs

**Comment by sunnz** [comment]
I have done run `auth0_custom_domain` and `aws_route53_record` too but it is still pending verification when looking at `dashboard/../../tenant/custom_domains`

**Comment by sergiught** [comment]
Hello @nitrag, since the opening of this issue we have introduced the `custom_domain_verification` resource. You can find the docs at: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/custom_domain_verification. 

I'll be closing this issue down but if needed please reopen under https://github.com/auth0/terraform-provider-auth0 as this repo has moved over there.
