### ISSUE TITLE
From property in auth0_email_template resource is required, but it should allow empty string. 

### ISSUE THREAD

**Issue by leonfs** [alexkappa/terraform-provider-auth0#406]
### Description

At the moment, the `auth0_email_template` resource enforces the `from` property as required, which is the expected behaviour, but this field should allow an empty string, as this is the only configuration value possible when not using custom email providers.

See: https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_email_template.go#L48

### Terraform Version

```
Terraform 0.15.3
+ provider.auth0 0.21.0
```

### Affected Resource(s)

* auth0_email_template

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
```

### Expected Behavior

For an email template using Auth0 email provider to be created when the `from` property is an empty string. 

### Actual Behavior

Failure to create resource because when the `from` property is not set, the API validates it is missing. But when it is set, and the Auth0 email provider is used (instead of a custom one),  the API doesn't allow for this field to have a custom value.

**Comment by fearnyritchiebros** [comment]
This actually isn't a problem with the Terraform Provider; the problem actually stems from one of it's dependencies.

Under the hood, this Provider uses the [Auth0 Go SDK](https://github.com/go-auth0/auth0) to make calls to the Auth0 Management API.

It turns out that the [`EmailTemplate` Struct](https://github.com/go-auth0/auth0/blob/master/management/email_template.go#L15) makes use of the [`omitempty` tag](https://www.sohamkamani.com/golang/omitempty/).  This means that any fields that are empty will be omitted from the request that is sent to the Management API.

I noticed the Management API returns this error only for `POST` and `PUT` requests, but not for `PATCH` requests.

The Auth0 Go SDK [uses `PATCH` requests](https://github.com/go-auth0/auth0/blob/master/management/email_template.go#L67) to **update** the templates; this means that until a PR is released to fix this problem, you can work around this problem by either creating the email templates outside of Terraform and them [importing them into Terraform](https://www.terraform.io/docs/cli/import/index.html), or you can create them with a non-empty string using Terraform, them modify the configuration and immediately run Terraform again.

The second run should update the templates using a `PATCH` request, and thus not throw an error.

I'll eventually make a PR to fix this problem if I can find the time and someone else doesn't beat me to it.

**Comment by sergiught** [comment]
This relates to several other issues that are present within the provider and I have captured this along with the others within https://github.com/auth0/terraform-provider-auth0/issues/14. 

As this repo has moved over at https://github.com/auth0/terraform-provider-auth0 please open new issues over there from now on.
