### ISSUE TITLE
Is there an interest in forking this project?

### ISSUE THREAD

**Issue by adomokos** [alexkappa/terraform-provider-auth0#447]
Dear Auth0 terraform community,

is there a desire/support forking this project? The last release was on April 25th, 2021, 148 days ago.
Auth0 has been releasing new features, but I have to configure our Auth0 tenant manually as this tf provider appears to be stale.
I requested official support from Auth0 for this provider, but that request did not go far. I believe there is a strong enough community to support the effort.

If there is a fork I am not aware of, please let me know.

If you're interested in a fork, please respond with 👍 . Thank you! :100:

**Comment by alekc** [comment]
@adomokos This is what I ended up doing at the end. 

Currently published version of auth0 had some severe bugs which were breaking our pipelines, even though PR fixing those bugs were available for couple of months now, they were not merged or reviewed. Also, new bits like actions and flows were missing as well. 

So I ended up forking the current implementation (https://github.com/alekc/terraform-provider-auth0), brought in majority of PRs up here, fixed some tickets, etc. 

In the fork there was one major releases (move to new terraform SDK, and changes in `auth_email` where options have been moved to their explicit blocks), and soon there will be another one doing the same for the auth0_connections, since currently it's a giant mess with scattered options rendering the usage very difficult.

**Comment by cw-sakamoto** [comment]
@alekc 

We have recently been considering using this provider, but we want to use `ACTION` and are wondering if we should use @alekc provider.

>Currently published version of auth0 had some severe bugs which were breaking our pipelines

Can you please tell me which PRs(or issues) ?

**Comment by alekc** [comment]
On top of my mind there were these:
https://github.com/alexkappa/terraform-provider-auth0/issues/380 : once the branding is enabled, terraform provider crashes in plan phase thus preventing you from doing anything

Some drifting issue especially on import of connections (due to the fact that option is not required).

**Comment by adomokos** [comment]
@alekc - I switched over to your provider. Thanks for your work on that!

**Comment by alekc** [comment]
In my experience Auth0 has a weird attitude towards their API and 3d party. Documentation on them is a mess in most of cases, they are breaking their own api and states that they won't fix it.

 I've also contacted them on several channels asking for a license which would permit me to test their enterprise offering (I even stated that to avoid any doubt of misuse they could've limited the amount of active users to 20 or so), but they've ignored all messages.

**Comment by adomokos** [comment]
Not to worry! The space is heating up, other competitors will emerge.

**Comment by wadenick** [comment]
Hello everyone, Nick from Auth0 here. We’re working closely with @alexkappa, as the author and current maintainer of terraform-provider-auth0, on bringing the newer Auth0 features to the provider soon. We’ll have even more good news to share in the near future, in order to ensure terraform-provider-auth0 has the coverage and support you need. Keep an eye on this repo. -nick wade, Product @ Auth0

**Comment by pete2786** [comment]
@wadenick Do you have an update here? I contacted our sales rep as well, did not see anything in the auth0 forums. Would be wonderful to get back to using terraform to manage our Auth0 resources.

**Comment by willvedd** [comment]
@pete2786 Our team is currently in the midst of transferring this project over to the Auth0 organization. It's a surprising amount of work and several hoops we still need to jump through. In the meantime, we've been reviewing PRs, issues and assembling a rough roadmap for the provider. Hopefully we'll have something more official to share in the coming days!

**Comment by adomokos** [comment]
@willvedd - that's good to hear. I complained many times to the Solution Architect I had worked with about the lack of sponsorship on Auth0's part for this project.

**Comment by sergiught** [comment]
Hello everyone, apologies for the time it took to get to this point. We really appreciate everyone's patience and input on this.

We have moved @alexkappa 's **terraform-provider-auth0** repo under the Auth0 org and are now officially supporting this project over here: https://github.com/auth0/terraform-provider-auth0.

You can already start using it as follows:

```hcl
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.27.0"
    }
  }
}

provider "auth0" {}
```

I'm currently in the process of taking a full pass on all the open issues over here and as soon as that's done we'll be moving forward with transferring all of them over to the new repository: https://github.com/auth0/terraform-provider-auth0 to not lose track of all the valuable input from all of you. 

Our team within Auth0 is taking full ownership of this and will ensure issues and PRs are addressed in a timely manner from now on.

Again, we really appreciate the community that has been growing around this Auth0 terraform provider and the support offered thus far and we look forward in strengthening the relationship we have further. 

Due to the above, I'll be closing this issue and from now on please open new ones over at https://github.com/auth0/terraform-provider-auth0. 

Big thank you to @alexkappa for his efforts in maintaining this thus far and also a big big big thank you to  every single one of you ❤️
