### ISSUE TITLE
Which Terraform resource covers "Machine to Machine Applications" under the applications page?

### ISSUE THREAD

**Issue by bourbonfgiles** [alexkappa/terraform-provider-auth0#520]
Just trying to ensure I get everything into state! 

Thanks.

**Comment by sergiught** [comment]
Hey @bourbonfgiles, the resource you're looking for should be the `auth0_client` one. As this should be enough for you to move forward and because we're in the process of transferring all the issues over to https://github.com/auth0/terraform-provider-auth0 I'll be closing this down. Please open a new one if needed over there.
