### ISSUE TITLE
Feature request: Support Authorization Extension

### ISSUE THREAD

**Issue by charlyinalbon** [alexkappa/terraform-provider-auth0#85]
We are using the authorization extension. Would be great if this can be terraformed as well.

docs: https://auth0.com/docs/extensions/authorization-extension/v2
api: https://auth0.com/docs/api/authorization-extension#introduction

**Comment by alexkappa** [comment]
Hi @charlyinalbon, the extension is largely a standalone app deployed in webtasks (a sister project of auth0). It communicates via auth0's api via rules as far as I can tell, so that part you can already do with this provider.

It was requested previously to support the webtasks api from this provider but I believe it is out of scope for this project.

**Comment by r24mille** [comment]
Good news on this issue! Role-Based Access Control was announced via a Support Center notification 12 days ago. The Authorization Extension is being phased out during 2019 in favor of an "Authorization Core" feature. They've started with Role-Based Access Control.

https://auth0.com/docs/authorization/concepts/rbac#role-based-access-control-in-auth0

So I think authorization may be a more tractable problem in the Terraform provider as it gets rolled into their core product.

**Comment by alexkappa** [comment]
Good news indeed! I'll give some time if there are any takers to add support for roles in the go sdk, otherwise I'll try to take a stab at it soon.

This is definitely something that belongs in the provider, no doubt.

**Comment by ltiessen** [comment]
I see you added the roles support in the go sdk @alexkappa (https://github.com/go-auth0/auth0/pull/37), any chance you've had time or will soon have time to add that support to this provider?

**Comment by charlieegan3** [comment]
I feel like this should be reopened as #121 isn't related to the supporting of the configuration of the Authorization Extension.

The extension provides some features not yet in Authorization Core such as Groups - see its own API here: https://auth0.com/docs/api/authorization-extension#introduction

Given authentication against the plugin is different, as is the API. I wonder if this is best suited to being handled by this provider at all...

**Comment by alexkappa** [comment]
@charlesjohnson there is no plan to support the authorization extension through this provider. 

The authorization extension relies on a product (https://webtask.io/) that to my knowledge is not publicly documented and is no longer supported outside of the auth0 dashboard. I wouldn't even know how to authenticate with this system.

**Comment by charlesjohnson** [comment]
Extensions are currently unsupported by the Terraform provider because the Auth0 management API does not have endpoints for managing extensions. There are no plans in the 3-6 month time frame to extend the management API with extensions support.

Customers with an Auth0 enterprise account can manage extensions using the `wt-cli` application. This capability is not enabled by default, ask your technical account manager to enable this ability for you. Automating extensions will require additional scripting outside of Terraform.

The wt-cli documentation is currently hosted at webtask.io. However, using or managing extensions with Auth0 does not require a webtask.io account.

What other questions can I answer for you?

**Comment by charlieegan3** [comment]
Thanks for the responses guys. That’s all totally understandable - just wanted to leave a clear end here in case anyone else found themselves looking at this in the future. Hopefully authorisation core will support groups before too long...
